SneakerSaver/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/sneakers/create', 'SneakerController@create');

Route::get('/sneakers', 'SneakerController@index');

Route::resource('sneakers', 'SneakerController');

SneakerSaver/app/Sneaker.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sneaker extends Model
{
    //
    protected $fillable = [
        'title',
        'material',
        'user_id'
    ];

    public function user(){
        return $this->belongsTo('App\User');
    }

//    public function bid(){
//        return $this->hasMany('App\Bid');
//    }

    public function saveSneakerToDB($data){
        $this->user_id = auth()->user()->id;
        $this->title = $data['title'];
        $this->material = $data['material'];
        $this->save();
        return 1;
    }
}

SneakerSaver/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function sneakers(){
        return $this->hasMany('App\Sneaker');
    }
}

SneakerSaver/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

SneakerSaver/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Gmopx\LaravelOWM\LaravelOWM;
use App\Sneaker;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sneakers = Sneaker::where('user_id', Auth::id())->get()->where('lastwornon', !'0');
        $lastSneakers = Sneaker::where('user_id', Auth::id())->orderBy('timesworn', 'desc')->get();

        $lowm = new LaravelOWM();
        $forecast = $lowm->getWeatherForecast('rotterdam');

        return view('home', ['weather' => $forecast, 'sneakers' => $sneakers, 'lastsneakers' => $lastSneakers]);
//        return view('home');
    }
}

SneakerSaver/app/Http/Controllers/SneakerController.php
<?php

namespace App\Http\Controllers;

use App\Sneaker;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class SneakerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if(Auth::check()){
            $sneakers = Sneaker::where('user_id', Auth::id())->get();

            return view('sneakers.index', ['sneakers' => $sneakers]);
        }else{
            return redirect('/welcome');
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        if (Auth::check()) {
            return view('sneakers.create');
        }else{
            return redirect('/welcome');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $sneaker = new Sneaker();
        $data = $this->validate($request, [
            'title' => 'required',
            'material' => 'required',
        ]);

        $sneaker->saveSneakerToDB($data);
        return redirect('/home')->with('success', 'New sneaker added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Sneaker $sneaker)
    {
        //
        if(Auth::check()){
            $sneaker = Sneaker::where('id', $sneaker->id)->first();

            return view('sneakers.show', ['sneaker' => $sneaker]);
        }else{
            return redirect('welcome');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Sneaker $sneaker)
    {
        //
        if(Auth::check()){
            $sneaker = Sneaker::where('id', $sneaker->id)->where('user_id', auth()->user()->id)->first();

            return view('sneakers.edit', ['sneaker' => $sneaker]);
        }else{
            return redirect('welcome');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sneaker $sneaker)
    {
        date_default_timezone_set('Europe/Amsterdam');
        //
        //Find sneaker with the same ID and update the title, description and price
        $i = 0;
        $sneakerUpdate = Sneaker::where('id', $sneaker->id)
            ->where('user_id', auth()->user()->id)
            ->update([
                'title' => $request->input('title'),
                'material' => $request->input('material'),
                'lastwornon' => $request->input('lastwornon'),
                'timesworn' => DB::raw('timesworn + 1')
            ]);

        //If it it successfully updated, redirect to route
        if($sneakerUpdate){
            return redirect()->route('sneakers.show', ['sneaker'=>$sneaker->id])->with('success', 'The sneaker page is updated!');
        }

        //If all fails, take us back to the page that brought us here
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        if(Auth::check()){
            $sneaker = Sneaker::find($id);
            $sneaker->delete();

            return redirect('/sneakers')->with('success', 'Sneaker successfully deleted.');
        }else{
            return redirect('welcome');
        }
    }
}

SneakerSaver/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            @php
                $i = 0;
                foreach ($weather as $weer) {
                                            $i++;
                    if($i == 1) {
                        echo "Temperature for first 3 hours " . $weer->temperature . "<br />";
                        echo "Summary: " . $weer->weather . "<br />";
                        if (strpos($weer->weather, 'rain') !== false) {
                            echo 'The weather is dirty! Spray in your shoes!<br />';
                        }
                        echo "---<br />\n";
                    }


                    if($i == 2){
                        continue;
                    }

                    if($i == 3){
                        echo "Temperature 6 hours later is " . $weer->temperature . "<br />";
                        echo "Summary: " . $weer->weather . "<br />";
                        echo "---<br />\n";
                        break;
                        }

                    //if($i == 3) break;
                }
            @endphp

            @foreach($sneakers as $sneaker)

                <h4>Currently wearing:</h4>
                <img src="img/SneakerSaver-Logo.png" alt="Sneaker">
                <p>{{ $sneaker->title }} since {{ $sneaker->lastwornon }}</p>
                @php
                    $dateThen = strtotime($sneaker->lastwornon);
                    $dateLater = strtotime("+2 weeks", $dateThen);

                $current = strtotime('now');

                $percentage = (($current - $dateThen) / ($dateLater - $dateThen)) * 100;

                $realPercentage = 100 - $percentage;

                @endphp
                <p>Time until next spray: {{ date('d-m-Y', $dateLater) }}</p>
                <p>{{ round($realPercentage, 2) }}% protected.</p>
                @if($realPercentage < '20.00')
                <p>Almost time to spray them in again!</p>
                @endif

            @endforeach
            <form method="post" action="{{ route('sneakers.update', [$sneaker->id]) }}" style="margin-bottom:10px;">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="put">
                <input type="hidden" name="title" value="{{ $sneaker->title }}">
                <input type="hidden" name="material" value="{{ $sneaker->material }}">
                <input type="hidden" name="lastwornon" value="0">
                <button type="submit" class="btn btn-warning">Take Off!</button>
            </form>
            @php
            $j = 0;
            @endphp
            @foreach($lastsneakers as $ls)
                @php
                $j++;
                @endphp
                <div class="col-xs-4">
                    <p>{{ $ls->title }}</p>
                    <p>Times worn: {{ $ls->timesworn }}</p>
                </div>
            @endforeach
            <div class="col-xs-12">
                <a href="{{ url('sneakers/create') }}" style="margin-right:7px;"><button class="btn btn-success">Add A Sneaker</button></a>
                <a href="{{ url('sneakers') }}"><button class="btn btn-primary">View All Sneakers</button></a>
            </div>
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
        </div>
    </div>
</div>
@endsection

SneakerSaver/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <style>

        body{
            background: #C4C4C4;
        }

        img{
            width: 100%;
        }

        #welcomeLogin{
            text-align: center;
            margin-bottom: 40px;
        }

        .imageWrapper{
            margin-bottom: 100px;
        }

        .registerWrapper{
            margin-top: -20px;
        }

        .shoeCard{
            min-height: 450px;
        }

        .btn1{
            margin-bottom:10px;
        }


    </style>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/home') }}">
                        {{--{{ config('app.name', 'Laravel') }}--}}
                        SneakerSaver
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ url('sneakers') }}">My Sneakers</a>
                                    </li>
                                    <li>
                                        <a href="{{ url('sneakers/create') }}">Create Sneaker</a>
                                    </li>
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>

                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

SneakerSaver/resources/views/sneakers/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-9">
                <form method="post" action="{{ route('sneakers.store') }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="sneaker-title">Title</label>
                        <input type="text" class="form-control" id="sneaker-title" placeholder="Enter Title" required value="" name="title">
                    </div>
                    <div class="form-group">
                        <label for="sneaker-material">Material</label>
                        <input type="text" class="form-control" id="sneaker-material" placeholder="Enter Material" required value="" name="material">
                    </div>
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
@endsection

SneakerSaver/resources/views/sneakers/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-9">
                <form method="post" action="{{ route('sneakers.update', [$sneaker->id]) }}">
                    {{ csrf_field() }}

                    <input type="hidden" name="_method" value="put">
                    <div class="form-group">
                        <label for="sneaker-title">Title</label>
                        <input type="text" class="form-control" id="sneaker-title" placeholder="Enter Title" required value="{{ $sneaker->title }}" name="title">
                    </div>
                    <div class="form-group">
                        <label for="sneaker-material">material</label>
                        <input type="text" class="form-control" id="sneaker-material" placeholder="Enter Material" required value="{{ $sneaker->material }}" name="material">
                        {{--<textarea class="form-control" id="sneaker-material" placeholder="Enter material" style="resize: vertical" name="material">--}}
                        {{--{{ $sneaker->material }}--}}
                    {{--</textarea>--}}
                    </div>
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                </form>
            </div>
        </div>
    </div>

@endsection

SneakerSaver/resources/views/sneakers/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <a href="{{ url('sneakers/create') }}"><button class="btn btn-primary pull-right">Add A Sneaker</button></a>
        </div>
        <div class="row">
            @foreach($sneakers as $sneaker)
                <div class="col-xs-6 shoeCard">
                    <div class="card" style="">
                        <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                        <div class="card-body">
                            <h4 class="card-title">{{$sneaker->title}}</h4>
                            <h4 class="card-title">Material: {{$sneaker->material}}</h4>
                            <img src="img/SneakerSaver-Logo.png" alt="sneaker">
                            <a href="{{ url('sneakers/' . $sneaker->id) }}" class="btn btn-primary btn1">View More</a>
                            <form method="post" action="{{ route('sneakers.update', [$sneaker->id]) }}">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="put">
                                <input type="hidden" name="title" value="{{ $sneaker->title }}">
                                <input type="hidden" name="material" value="{{ $sneaker->material }}">
                                <input type="hidden" name="lastwornon" value="{{ date('d-m-Y H:i') }}">
                                <button type="submit" class="btn btn-primary btn1">Wear Now!</button>
                            </form>
                            @if($sneaker->lastwornon != '0')
                                <form method="post" action="{{ route('sneakers.update', [$sneaker->id]) }}">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="put">
                                    <input type="hidden" name="title" value="{{ $sneaker->title }}">
                                    <input type="hidden" name="material" value="{{ $sneaker->material }}">
                                    <input type="hidden" name="lastwornon" value="0">
                                    <button type="submit" class="btn btn-primary btn1">Take Off!</button>
                                </form>
                            @endif
                            <h5>Wearing since: {{ $sneaker->lastwornon }}</h5>
                            <h5>Worn {{ $sneaker->timesworn }} times.</h5>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

SneakerSaver/resources/views/sneakers/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-9">
                <div class="card" style="">
                    <!-- <img class="card-img-top" src="..." alt="Card image cap" src="https://dummyimage.com/600x400/000/fff"> -->
                    <div class="card-body">
                        <h4 class="card-title">{{$sneaker->title}}</h4>
                        <h4 class="card-title">{{$sneaker->material}}</h4>
                        <hr>
                        <h4>
                            @php

                                if($sneaker->lastwornon != "0")
                                {
                                    echo "Currently wearing shoe since " . $sneaker->lastwornon . ".";
                                }

                            @endphp
                        </h4>
                        <div class="bids">
                            <ul class="list-group">
                                {{--@foreach($sneaker->bid as $bid)--}}
                                    {{--<li class="list-group-item">--}}
                                        {{--<strong>{{ $bid->created_at->diffForHumans() }}:</strong> &nbsp;--}}
                                        {{--€{{ $bid->bid }} by: {{ $bid->user->name }}--}}
                                    {{--</li>--}}
                                {{--@endforeach--}}
                            </ul>
                        </div>

                        <hr>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <div class="">
                    <h4>Actions</h4>
                    @if(auth()->user()->id == $sneaker->user_id)
                        <ol class="list-unstyled">
                            {{--<li><a href="{{ url('sneakers/' . $sneaker->id . '/edit') }}">Edit Post</a></li>--}}
                            <li><a href="{{ url('sneakers/create') }}">Add A Sneaker</a></li>
                            <li><a href="{{ url('sneakers') }}">View All Sneakers</a></li>
                            <br/>
                            <form action="{{action('SneakerController@destroy', $sneaker->id)}}" method="post">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">
                                <button class="btn btn-danger" type="submit">Delete This Sneaker</button>
                            </form>
                        </ol>
                    @else
                        <ol class="list-unstyled">
                            <li><a href="{{ url('sneakers/create') }}">Add A Sneaker</a></li>
                            <li><a href="{{ url('sneakers') }}">View All Sneakers</a></li>
                        </ol>
                    @endif
                </div>
            </div>
        </div>
    </div>

@endsection